FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements.txt into the container
COPY requirements.txt .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
        gcc \
        libmariadb-dev-compat \
        libmariadb-dev \
        pkg-config \
        --no-install-recommends && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy your application code
COPY . .

# Expose port 8000
EXPOSE 8000

# Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]