version: "3.8"

services:
  web:
    build: .
    container_name: django_app
    # Replace the command to wait for MySQL before starting Django
    command: >
      sh -c "./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./wait-for-it.sh:/wait-for-it.sh # Mount the wait-for-it script
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
