pipeline {
    agent any

    stages {
        stage('Checkout code') {
            steps {
                git branch: 'main', credentialsId: 'bce871e4-3bfd-4ea5-bf52-e9f8cd024735', url: 'https://github.com/leticiaikemeh/alx-backend-python.git'
            }
        }
        stage('Set up venv & Install dependencies') {
            steps {
                dir('messaging_app') {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Run tests') {
            steps {
                dir('messaging_app') {
                    sh '''
                        . venv/bin/activate
                        pytest --junitxml=test-results.xml
                    '''
                }
            }
            post {
                always {
                    junit 'messaging_app/test-results.xml'
                }
            }
        }
    }
}
